os:
  - linux
  - osx
before_script: curl https://raw.githubusercontent.com/chiefbiiko/deno-bash-installer/master/install.sh | sudo bash
script: deno --allow-write ./test.ts ./mkdirptest
after_script: rm -rf ./mkdirptest